﻿Console.Clear();
Console.Write("Введите координаты:");
Console.Write("X1= ");
int x1 = Convert.ToInt32(Console.ReadLine());
Console.Write("Y1= ");
int y1 = Convert.ToInt32(Console.ReadLine());
Console.Write("Z1= ");
int z1 = Convert.ToInt32(Console.ReadLine());
Console.Write("X2= ");
int x2 = Convert.ToInt32(Console.ReadLine());
Console.Write("Y2= ");
int y2 = Convert.ToInt32(Console.ReadLine());
Console.Write("Z2= ");
int z2 = Convert.ToInt32(Console.ReadLine());
    Console.WriteLine(Math.Sqrt(Math.Pow(x1 - x2, 2) + Math.Pow(y1 - y2, 2) + Math.Pow(z1 - z2, 2)));
